export type Instrument = {
  symbol: string;
  name: string;
  kind: "Akcie" | "ETF";
  market: string;
};

const S = (symbol: string, name: string, market: string): Instrument => ({
  symbol,
  name,
  kind: "Akcie",
  market,
});
const E = (symbol: string, name: string, market: string): Instrument => ({
  symbol,
  name,
  kind: "ETF",
  market,
});

export const UNIVERSE: Instrument[] = [
  // ---- US technologie
  S("AAPL", "Apple Inc.", "US"),
  S("MSFT", "Microsoft Corp.", "US"),
  S("NVDA", "NVIDIA Corp.", "US"),
  S("GOOGL", "Alphabet Inc. A", "US"),
  S("AMZN", "Amazon.com Inc.", "US"),
  S("META", "Meta Platforms", "US"),
  S("TSLA", "Tesla Inc.", "US"),
  S("AVGO", "Broadcom Inc.", "US"),
  S("AMD", "Advanced Micro Devices", "US"),
  S("INTC", "Intel Corp.", "US"),
  S("QCOM", "Qualcomm Inc.", "US"),
  S("TXN", "Texas Instruments", "US"),
  S("MU", "Micron Technology", "US"),
  S("ADBE", "Adobe Inc.", "US"),
  S("CRM", "Salesforce Inc.", "US"),
  S("ORCL", "Oracle Corp.", "US"),
  S("IBM", "IBM Corp.", "US"),
  S("CSCO", "Cisco Systems", "US"),
  S("NOW", "ServiceNow Inc.", "US"),
  S("SNOW", "Snowflake Inc.", "US"),
  S("PLTR", "Palantir Technologies", "US"),
  S("UBER", "Uber Technologies", "US"),
  S("ABNB", "Airbnb Inc.", "US"),
  S("SHOP", "Shopify Inc.", "US"),
  S("SQ", "Block Inc.", "US"),
  S("PYPL", "PayPal Holdings", "US"),
  S("NFLX", "Netflix Inc.", "US"),
  S("DIS", "Walt Disney Co.", "US"),
  S("SPOT", "Spotify Technology", "US"),
  S("RBLX", "Roblox Corp.", "US"),
  S("COIN", "Coinbase Global", "US"),
  S("MSTR", "MicroStrategy Inc.", "US"),
  S("ARM", "Arm Holdings", "US"),
  S("SMCI", "Super Micro Computer", "US"),
  S("DELL", "Dell Technologies", "US"),
  S("HPQ", "HP Inc.", "US"),
  S("ZM", "Zoom Communications", "US"),
  S("DDOG", "Datadog Inc.", "US"),
  S("NET", "Cloudflare Inc.", "US"),
  S("CRWD", "CrowdStrike Holdings", "US"),
  S("PANW", "Palo Alto Networks", "US"),
  S("FTNT", "Fortinet Inc.", "US"),
  S("ANET", "Arista Networks", "US"),
  S("MRVL", "Marvell Technology", "US"),
  S("LRCX", "Lam Research", "US"),
  S("KLAC", "KLA Corp.", "US"),
  S("AMAT", "Applied Materials", "US"),
  S("ADI", "Analog Devices", "US"),
  S("ON", "ON Semiconductor", "US"),
  S("NXPI", "NXP Semiconductors", "US"),
  S("WDAY", "Workday Inc.", "US"),
  S("TEAM", "Atlassian Corp.", "US"),
  S("HUBS", "HubSpot Inc.", "US"),
  S("TTD", "The Trade Desk", "US"),
  S("APP", "AppLovin Corp.", "US"),
  S("TWLO", "Twilio Inc.", "US"),
  S("OKTA", "Okta Inc.", "US"),
  S("MDB", "MongoDB Inc.", "US"),
  S("U", "Unity Software", "US"),
  S("DASH", "DoorDash Inc.", "US"),
  S("PINS", "Pinterest Inc.", "US"),
  S("SNAP", "Snap Inc.", "US"),
  S("LYFT", "Lyft Inc.", "US"),
  S("EA", "Electronic Arts", "US"),
  S("TTWO", "Take-Two Interactive", "US"),
  S("ADSK", "Autodesk Inc.", "US"),
  S("INTU", "Intuit Inc.", "US"),

  // ---- US finance
  S("JPM", "JPMorgan Chase", "US"),
  S("BAC", "Bank of America", "US"),
  S("WFC", "Wells Fargo", "US"),
  S("GS", "Goldman Sachs", "US"),
  S("MS", "Morgan Stanley", "US"),
  S("C", "Citigroup Inc.", "US"),
  S("BLK", "BlackRock Inc.", "US"),
  S("V", "Visa Inc.", "US"),
  S("MA", "Mastercard Inc.", "US"),
  S("AXP", "American Express", "US"),
  S("BRK-B", "Berkshire Hathaway B", "US"),
  S("SCHW", "Charles Schwab", "US"),
  S("PGR", "Progressive Corp.", "US"),
  S("TRV", "Travelers Companies", "US"),
  S("MET", "MetLife Inc.", "US"),
  S("PRU", "Prudential Financial", "US"),
  S("AIG", "American International Group", "US"),
  S("USB", "US Bancorp", "US"),
  S("PNC", "PNC Financial Services", "US"),
  S("TFC", "Truist Financial", "US"),
  S("COF", "Capital One Financial", "US"),
  S("SOFI", "SoFi Technologies", "US"),
  S("AFRM", "Affirm Holdings", "US"),
  S("ICE", "Intercontinental Exchange", "US"),
  S("CME", "CME Group Inc.", "US"),
  S("SPGI", "S&P Global Inc.", "US"),
  S("MCO", "Moody's Corp.", "US"),

  // ---- US zdravotnictví a biotech
  S("JNJ", "Johnson & Johnson", "US"),
  S("LLY", "Eli Lilly & Co.", "US"),
  S("PFE", "Pfizer Inc.", "US"),
  S("MRK", "Merck & Co.", "US"),
  S("ABBV", "AbbVie Inc.", "US"),
  S("UNH", "UnitedHealth Group", "US"),
  S("AMGN", "Amgen Inc.", "US"),
  S("MRNA", "Moderna Inc.", "US"),
  S("GILD", "Gilead Sciences", "US"),
  S("CVS", "CVS Health", "US"),
  S("ISRG", "Intuitive Surgical", "US"),
  S("VRTX", "Vertex Pharmaceuticals", "US"),
  S("REGN", "Regeneron Pharmaceuticals", "US"),
  S("BIIB", "Biogen Inc.", "US"),
  S("ZTS", "Zoetis Inc.", "US"),
  S("BSX", "Boston Scientific", "US"),
  S("MDT", "Medtronic plc", "US"),
  S("SYK", "Stryker Corp.", "US"),
  S("HCA", "HCA Healthcare", "US"),
  S("ELV", "Elevance Health", "US"),
  S("CI", "The Cigna Group", "US"),
  S("HUM", "Humana Inc.", "US"),
  S("BMY", "Bristol Myers Squibb", "US"),
  S("DXCM", "DexCom Inc.", "US"),
  S("IDXX", "IDEXX Laboratories", "US"),

  // ---- US spotřeba a průmysl
  S("KO", "Coca-Cola Co.", "US"),
  S("PEP", "PepsiCo Inc.", "US"),
  S("PG", "Procter & Gamble", "US"),
  S("MCD", "McDonald's Corp.", "US"),
  S("SBUX", "Starbucks Corp.", "US"),
  S("NKE", "Nike Inc.", "US"),
  S("WMT", "Walmart Inc.", "US"),
  S("COST", "Costco Wholesale", "US"),
  S("TGT", "Target Corp.", "US"),
  S("HD", "Home Depot", "US"),
  S("LOW", "Lowe's Companies", "US"),
  S("BA", "Boeing Co.", "US"),
  S("CAT", "Caterpillar Inc.", "US"),
  S("DE", "Deere & Co.", "US"),
  S("GE", "GE Aerospace", "US"),
  S("LMT", "Lockheed Martin", "US"),
  S("RTX", "RTX Corp.", "US"),
  S("HON", "Honeywell International", "US"),
  S("UPS", "United Parcel Service", "US"),
  S("F", "Ford Motor Co.", "US"),
  S("GM", "General Motors", "US"),
  S("RIVN", "Rivian Automotive", "US"),
  S("LCID", "Lucid Group", "US"),
  S("YUM", "Yum! Brands", "US"),
  S("CMG", "Chipotle Mexican Grill", "US"),
  S("DPZ", "Domino's Pizza", "US"),
  S("EL", "Estée Lauder Companies", "US"),
  S("CL", "Colgate-Palmolive", "US"),
  S("KMB", "Kimberly-Clark Corp.", "US"),
  S("MDLZ", "Mondelez International", "US"),
  S("MNST", "Monster Beverage", "US"),
  S("KHC", "Kraft Heinz Co.", "US"),
  S("GIS", "General Mills Inc.", "US"),
  S("TJX", "TJX Companies", "US"),
  S("ROST", "Ross Stores", "US"),
  S("ULTA", "Ulta Beauty", "US"),
  S("LULU", "Lululemon Athletica", "US"),
  S("ETSY", "Etsy Inc.", "US"),
  S("EBAY", "eBay Inc.", "US"),
  S("MMM", "3M Company", "US"),
  S("EMR", "Emerson Electric", "US"),
  S("ETN", "Eaton Corp.", "US"),
  S("PH", "Parker Hannifin", "US"),
  S("ITW", "Illinois Tool Works", "US"),
  S("PCAR", "PACCAR Inc.", "US"),
  S("FDX", "FedEx Corp.", "US"),
  S("NSC", "Norfolk Southern", "US"),
  S("UNP", "Union Pacific Corp.", "US"),
  S("CSX", "CSX Corp.", "US"),

  // ---- US energie a suroviny
  S("XOM", "Exxon Mobil", "US"),
  S("CVX", "Chevron Corp.", "US"),
  S("COP", "ConocoPhillips", "US"),
  S("SLB", "SLB (Schlumberger)", "US"),
  S("OXY", "Occidental Petroleum", "US"),
  S("FCX", "Freeport-McMoRan", "US"),
  S("NEM", "Newmont Corp.", "US"),
  S("NEE", "NextEra Energy", "US"),
  S("ENPH", "Enphase Energy", "US"),
  S("FSLR", "First Solar", "US"),
  S("EOG", "EOG Resources", "US"),
  S("PXD", "Pioneer Natural Resources", "US"),
  S("KMI", "Kinder Morgan", "US"),
  S("WMB", "Williams Companies", "US"),
  S("DUK", "Duke Energy", "US"),
  S("SO", "Southern Company", "US"),
  S("AEP", "American Electric Power", "US"),
  S("D", "Dominion Energy", "US"),
  S("LIN", "Linde plc", "US"),
  S("APD", "Air Products and Chemicals", "US"),
  S("SHW", "Sherwin-Williams", "US"),
  S("ECL", "Ecolab Inc.", "US"),
  S("DOW", "Dow Inc.", "US"),

  // ---- US telekom, média, ostatní, REIT
  S("T", "AT&T Inc.", "US"),
  S("VZ", "Verizon Communications", "US"),
  S("TMUS", "T-Mobile US", "US"),
  S("CMCSA", "Comcast Corp.", "US"),
  S("WBD", "Warner Bros. Discovery", "US"),
  S("PARA", "Paramount Skydance", "US"),
  S("DAL", "Delta Air Lines", "US"),
  S("AAL", "American Airlines", "US"),
  S("UAL", "United Airlines Holdings", "US"),
  S("LUV", "Southwest Airlines", "US"),
  S("CCL", "Carnival Corp.", "US"),
  S("RCL", "Royal Caribbean Cruises", "US"),
  S("MAR", "Marriott International", "US"),
  S("HLT", "Hilton Worldwide", "US"),
  S("BKNG", "Booking Holdings", "US"),
  S("EXPE", "Expedia Group", "US"),
  S("AMT", "American Tower Corp.", "US"),
  S("PLD", "Prologis Inc.", "US"),
  S("EQIX", "Equinix Inc.", "US"),
  S("O", "Realty Income Corp.", "US"),
  S("SPG", "Simon Property Group", "US"),
  S("PSA", "Public Storage", "US"),
  S("DLR", "Digital Realty Trust", "US"),

  // ---- Německo (XETRA)
  S("SAP.DE", "SAP SE", "DE"),
  S("SIE.DE", "Siemens AG", "DE"),
  S("ALV.DE", "Allianz SE", "DE"),
  S("DTE.DE", "Deutsche Telekom", "DE"),
  S("BAS.DE", "BASF SE", "DE"),
  S("BAYN.DE", "Bayer AG", "DE"),
  S("BMW.DE", "BMW AG", "DE"),
  S("MBG.DE", "Mercedes-Benz Group", "DE"),
  S("VOW3.DE", "Volkswagen AG Pref.", "DE"),
  S("DBK.DE", "Deutsche Bank", "DE"),
  S("ADS.DE", "adidas AG", "DE"),
  S("RWE.DE", "RWE AG", "DE"),
  S("IFX.DE", "Infineon Technologies", "DE"),
  S("AIR.DE", "Airbus SE", "DE"),
  S("RHM.DE", "Rheinmetall AG", "DE"),
  S("MUV2.DE", "Munich Re", "DE"),
  S("DPW.DE", "Deutsche Post AG", "DE"),
  S("HEN3.DE", "Henkel AG Pref.", "DE"),
  S("FRE.DE", "Fresenius SE", "DE"),
  S("VNA.DE", "Vonovia SE", "DE"),
  S("PUM.DE", "Puma SE", "DE"),
  S("CON.DE", "Continental AG", "DE"),
  S("HEI.DE", "Heidelberg Materials", "DE"),

  // ---- Francie / Nizozemsko / ostatní EU
  S("MC.PA", "LVMH", "FR"),
  S("OR.PA", "L'Oréal", "FR"),
  S("TTE.PA", "TotalEnergies", "FR"),
  S("SAN.PA", "Sanofi", "FR"),
  S("AI.PA", "Air Liquide", "FR"),
  S("BNP.PA", "BNP Paribas", "FR"),
  S("KER.PA", "Kering SA", "FR"),
  S("RMS.PA", "Hermès International", "FR"),
  S("SU.PA", "Schneider Electric", "FR"),
  S("CS.PA", "AXA SA", "FR"),
  S("DG.PA", "Vinci SA", "FR"),
  S("ASML.AS", "ASML Holding", "NL"),
  S("ADYEN.AS", "Adyen NV", "NL"),
  S("INGA.AS", "ING Groep", "NL"),
  S("HEIA.AS", "Heineken NV", "NL"),
  S("PHIA.AS", "Koninklijke Philips", "NL"),
  S("NESN.SW", "Nestlé SA", "CH"),
  S("NOVN.SW", "Novartis AG", "CH"),
  S("ROG.SW", "Roche Holding", "CH"),
  S("UBSG.SW", "UBS Group", "CH"),
  S("ZURN.SW", "Zurich Insurance Group", "CH"),
  S("NOVO-B.CO", "Novo Nordisk B", "DK"),
  S("MAERSK-B.CO", "A.P. Moller-Maersk B", "DK"),
  S("VOLV-B.ST", "Volvo B", "SE"),
  S("ERIC-B.ST", "Ericsson B", "SE"),
  S("HM-B.ST", "Hennes & Mauritz B", "SE"),
  S("EQNR.OL", "Equinor ASA", "NO"),
  S("ENI.MI", "Eni SpA", "IT"),
  S("ISP.MI", "Intesa Sanpaolo", "IT"),
  S("UCG.MI", "UniCredit SpA", "IT"),
  S("STLA.MI", "Stellantis NV", "IT"),
  S("ITX.MC", "Inditex SA", "ES"),
  S("SAN.MC", "Banco Santander", "ES"),
  S("IBE.MC", "Iberdrola SA", "ES"),

  // ---- UK
  S("SHEL.L", "Shell plc", "UK"),
  S("BP.L", "BP plc", "UK"),
  S("HSBA.L", "HSBC Holdings", "UK"),
  S("AZN.L", "AstraZeneca", "UK"),
  S("GSK.L", "GSK plc", "UK"),
  S("ULVR.L", "Unilever plc", "UK"),
  S("RR.L", "Rolls-Royce Holdings", "UK"),
  S("BARC.L", "Barclays plc", "UK"),
  S("DGE.L", "Diageo plc", "UK"),
  S("VOD.L", "Vodafone Group", "UK"),
  S("LLOY.L", "Lloyds Banking Group", "UK"),
  S("BATS.L", "British American Tobacco", "UK"),
  S("RIO.L", "Rio Tinto plc", "UK"),
  S("GLEN.L", "Glencore plc", "UK"),
  S("NG.L", "National Grid plc", "UK"),
  S("TSCO.L", "Tesco plc", "UK"),

  // ---- Praha (BCPP)
  S("CEZ.PR", "ČEZ a.s.", "CZ"),
  S("KOMB.PR", "Komerční banka", "CZ"),
  S("MONET.PR", "Moneta Money Bank", "CZ"),
  S("ERBAG.PR", "Erste Group Bank", "CZ"),
  S("PHOTON.PR", "Photon Energy", "CZ"),
  S("COLT.PR", "Colt CZ Group", "CZ"),
  S("VIG.PR", "Vienna Insurance Group", "CZ"),
  S("PMCR.PR", "Philip Morris ČR", "CZ"),
  S("STOCK.PR", "Stock Spirits Group", "CZ"),
  S("CETV.PR", "Central European Media", "CZ"),

  // ---- Kanada
  S("SHOP.TO", "Shopify Inc.", "CA"),
  S("RY.TO", "Royal Bank of Canada", "CA"),
  S("TD.TO", "Toronto-Dominion Bank", "CA"),
  S("ENB.TO", "Enbridge Inc.", "CA"),
  S("CNQ.TO", "Canadian Natural Resources", "CA"),
  S("BN.TO", "Brookfield Corp.", "CA"),
  S("BCE.TO", "BCE Inc.", "CA"),
  S("CNR.TO", "Canadian National Railway", "CA"),

  // ---- Austrálie
  S("BHP.AX", "BHP Group", "AU"),
  S("CBA.AX", "Commonwealth Bank", "AU"),
  S("CSL.AX", "CSL Limited", "AU"),
  S("WES.AX", "Wesfarmers Limited", "AU"),

  // ---- Asie / ostatní
  S("BABA", "Alibaba Group", "US"),
  S("JD", "JD.com Inc.", "US"),
  S("PDD", "PDD Holdings", "US"),
  S("NIO", "NIO Inc.", "US"),
  S("XPEV", "XPeng Inc.", "US"),
  S("LI", "Li Auto Inc.", "US"),
  S("BIDU", "Baidu Inc.", "US"),
  S("TCEHY", "Tencent Holdings ADR", "US"),
  S("TSM", "TSMC ADR", "US"),
  S("SONY", "Sony Group ADR", "US"),
  S("TM", "Toyota Motor ADR", "US"),
  S("HMC", "Honda Motor ADR", "US"),
  S("INFY", "Infosys ADR", "US"),
  S("WIT", "Wipro Ltd. ADR", "US"),
  S("HDB", "HDFC Bank ADR", "US"),
  S("SE", "Sea Limited ADR", "US"),
  S("GRAB", "Grab Holdings", "US"),
  S("005930.KS", "Samsung Electronics", "KR"),
  S("000660.KS", "SK Hynix", "KR"),
  S("9984.T", "SoftBank Group", "JP"),
  S("7203.T", "Toyota Motor Corp.", "JP"),
  S("6758.T", "Sony Group Corp.", "JP"),
  S("9432.T", "Nippon Telegraph", "JP"),

  // ---- ETF: široký trh
  E("SPY", "SPDR S&P 500 ETF", "US"),
  E("VOO", "Vanguard S&P 500 ETF", "US"),
  E("IVV", "iShares Core S&P 500", "US"),
  E("QQQ", "Invesco QQQ Trust", "US"),
  E("DIA", "SPDR Dow Jones ETF", "US"),
  E("IWM", "iShares Russell 2000", "US"),
  E("VTI", "Vanguard Total Stock Market", "US"),
  E("VT", "Vanguard Total World", "US"),
  E("ACWI", "iShares MSCI ACWI", "US"),
  E("EFA", "iShares MSCI EAFE", "US"),
  E("VEA", "Vanguard Developed Markets", "US"),
  E("VWO", "Vanguard Emerging Markets", "US"),
  E("EEM", "iShares MSCI Emerging Markets", "US"),
  E("IEUR", "iShares Core MSCI Europe", "US"),
  E("EWJ", "iShares MSCI Japan", "US"),
  E("EWG", "iShares MSCI Germany", "US"),
  E("MCHI", "iShares MSCI China", "US"),
  E("INDA", "iShares MSCI India", "US"),
  E("EWC", "iShares MSCI Canada", "US"),
  E("EWA", "iShares MSCI Australia", "US"),
  E("EWZ", "iShares MSCI Brazil", "US"),
  E("EWY", "iShares MSCI South Korea", "US"),
  E("RSP", "Invesco S&P 500 Equal Weight", "US"),

  // ---- ETF: sektory a témata
  E("XLK", "Technology Select Sector", "US"),
  E("XLF", "Financial Select Sector", "US"),
  E("XLE", "Energy Select Sector", "US"),
  E("XLV", "Health Care Select Sector", "US"),
  E("XLI", "Industrial Select Sector", "US"),
  E("XLY", "Consumer Discretionary Sector", "US"),
  E("XLP", "Consumer Staples Sector", "US"),
  E("XLU", "Utilities Select Sector", "US"),
  E("XLRE", "Real Estate Select Sector", "US"),
  E("XLB", "Materials Select Sector", "US"),
  E("XLC", "Communication Services Sector", "US"),
  E("SMH", "VanEck Semiconductor ETF", "US"),
  E("SOXX", "iShares Semiconductor ETF", "US"),
  E("ARKK", "ARK Innovation ETF", "US"),
  E("ARKG", "ARK Genomic Revolution ETF", "US"),
  E("ICLN", "iShares Global Clean Energy", "US"),
  E("TAN", "Invesco Solar ETF", "US"),
  E("LIT", "Global X Lithium & Battery", "US"),
  E("BOTZ", "Global X Robotics & AI", "US"),
  E("HACK", "Amplify Cybersecurity ETF", "US"),
  E("JETS", "US Global Jets ETF", "US"),
  E("ITA", "iShares US Aerospace & Defense", "US"),
  E("VNQ", "Vanguard Real Estate ETF", "US"),
  E("SCHD", "Schwab US Dividend Equity", "US"),
  E("VIG", "Vanguard Dividend Appreciation", "US"),
  E("VYM", "Vanguard High Dividend Yield", "US"),
  E("KWEB", "KraneShares CSI China Internet", "US"),
  E("XBI", "SPDR S&P Biotech ETF", "US"),
  E("IBB", "iShares Biotechnology ETF", "US"),
  E("XOP", "SPDR S&P Oil & Gas E&P", "US"),
  E("KRE", "SPDR S&P Regional Banking", "US"),
  E("XRT", "SPDR S&P Retail ETF", "US"),
  E("MOO", "VanEck Agribusiness ETF", "US"),
  E("URA", "Global X Uranium ETF", "US"),
  E("COPX", "Global X Copper Miners", "US"),

  // ---- ETF: dluhopisy a komodity
  E("AGG", "iShares Core US Aggregate Bond", "US"),
  E("BND", "Vanguard Total Bond Market", "US"),
  E("TLT", "iShares 20+ Year Treasury", "US"),
  E("IEF", "iShares 7-10 Year Treasury", "US"),
  E("SHY", "iShares 1-3 Year Treasury", "US"),
  E("HYG", "iShares High Yield Corporate", "US"),
  E("LQD", "iShares Investment Grade Corp.", "US"),
  E("TIP", "iShares TIPS Bond ETF", "US"),
  E("MUB", "iShares National Muni Bond", "US"),
  E("GLD", "SPDR Gold Shares", "US"),
  E("IAU", "iShares Gold Trust", "US"),
  E("SLV", "iShares Silver Trust", "US"),
  E("USO", "United States Oil Fund", "US"),
  E("UNG", "United States Natural Gas", "US"),
  E("DBC", "Invesco DB Commodity Index", "US"),
  E("PDBC", "Invesco Optimum Yield Commodity", "US"),
  E("PPLT", "abrdn Physical Platinum Shares", "US"),

  // ---- ETF: Evropa (UCITS)
  E("IWDA.AS", "iShares Core MSCI World UCITS", "NL"),
  E("EUNL.DE", "iShares Core MSCI World UCITS", "DE"),
  E("VUSA.AS", "Vanguard S&P 500 UCITS", "NL"),
  E("VWCE.DE", "Vanguard FTSE All-World UCITS", "DE"),
  E("EXS1.DE", "iShares Core DAX UCITS", "DE"),
  E("SXR8.DE", "iShares Core S&P 500 UCITS", "DE"),
  E("EIMI.L", "iShares Core EM IMI UCITS", "UK"),
  E("ISAC.L", "iShares MSCI ACWI UCITS", "UK"),
  E("CSPX.L", "iShares Core S&P 500 UCITS", "UK"),
  E("VFEM.L", "Vanguard FTSE EM UCITS", "UK"),
  E("EQQQ.L", "Invesco EQQQ Nasdaq-100 UCITS", "UK"),
];

export const UNIVERSE_BY_SYMBOL: Record<string, Instrument> = Object.fromEntries(
  UNIVERSE.map((i) => [i.symbol, i]),
);

export function searchUniverse(query: string, limit = 40): Instrument[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const scored = UNIVERSE.map((i) => {
    const sym = i.symbol.toLowerCase();
    const name = i.name.toLowerCase();
    let score = -1;
    if (sym === q) score = 0;
    else if (sym.startsWith(q)) score = 1;
    else if (name.toLowerCase().startsWith(q)) score = 2;
    else if (sym.includes(q)) score = 3;
    else if (name.includes(q)) score = 4;
    return { i, score };
  }).filter((x) => x.score >= 0);
  scored.sort((a, b) => a.score - b.score || a.i.symbol.localeCompare(b.i.symbol));
  return scored.slice(0, limit).map((x) => x.i);
}
